# Identificação
spring.application.name=api

# Banco de Dados (Preencher com dados locais)
spring.datasource.url=jdbc:postgresql://localhost:5432/NOME_DO_SEU_BANCO
spring.datasource.username=SEU_USUARIO
spring.datasource.password=SUA_SENHA
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA -
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Adiciona o /api antes das rotas da api
server.servlet.context-path=/api
springdoc.api-docs.path=/api-docs

# Segurança (Gerar uma chave aleatória segura)
api.security.token.secret=${JWT_SECRET:SuaChaveSeguraAqui}

# Logs de Erro
server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always