spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=senha123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
api.security.token.secret=zB5#vR92!mK7pQw4xN&8uE@1tYzL6vCjH9*sA3dB2nG5fV8rM
server.servlet.context-path=/api
server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always
